#
# from https://github.com/actions/starter-workflows/blob/master/ci/c-cpp.yml
#

name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install gcc-multilib
      run: |
          sudo apt update
          sudo apt install gcc-multilib -y
    - name: make
      run: make
    - name: make perl
      run: make perl
    - name: make test
      run: make test
    - name: copy x64
      run: |
        mkdir x64
        cp nkf x64
        cp libnkf32.so x64
    - name: make x86
      run: |
        make clean
        make -f Makefile_32
    - name: make test
      run: make test
    - name: copy x86
      run: |
        mkdir x86
        cp nkf x86
        cp libnkf32.so x86

    # Upload binary package: https://github.com/actions/upload-artifact
    - name: Upload artifact 
      uses: actions/upload-artifact@v2
      with:
        name: release-files
        path: |
            ${{ github.workspace }}/x86/nkf
            ${{ github.workspace }}/x86/libnkf32.so
            ${{ github.workspace }}/x64/nkf
            ${{ github.workspace }}/x64/libnkf32.so
